/** DO NOT EDIT MANUALLY, content generated by the script.
 * To regenerate just run `generate:icons:names` script from package.json
 */

export enum IconNames  {
  ICON_CHECK_CIRCLE = 'check-circle',
  ICON_X = 'x',
  ICON_EXCLAMATION = 'exclamation',
}

export const {
  ICON_CHECK_CIRCLE,
  ICON_EXCLAMATION,
  ICON_X,
} = IconNames;
