export const ORIENTATION = {
  LANDSCAPE: 'landscape',
  PORTRAIT: 'portrait',
};

export const PLATFORM = {
  PC: 'PC',
  MOBILE: 'MOBILE',
};

export const TYPE_NAME = {
  PAGE: 'PAGE',
  BLOCK: 'BLOCK',
  COMMON: 'COMMON',
  ALL_SITE: 'ALL_SITE',
};

export const SETTINGS = {
  BACKGROUND_COLOR: 'BACKGROUND_COLOR',
  LAYOUT_STRUCTURE: 'LAYOUT_STRUCTURE',
  BANNER_IMAGE: 'BANNER_IMAGE',
  CABLE_BANNER_IMAGE: 'CABLE_BANNER_IMAGE',
  LED_LIGHT_BANNER_IMAGE: 'LED_LIGHT_BANNER_IMAGE',
  INTRODUCTION_BLOCK: 'INTRODUCTION_BLOCK',
  IS_HIDDEN: 'IS_HIDDEN',
  IS_HIDDEN_PHONE_ICON: 'IS_HIDDEN_PHONE_ICON',
  FONT_SIZE: 'FONT_SIZE',
  LOGO: 'LOGO',
};

export const PAGE_NAME = {
  P_TEMPLATE: 'P_TEMPLATE',
  P_HOME: 'P_HOME',
  P_PRODUCT: 'P_PRODUCT',
  P_PRODUCT_CATEGORY: 'P_PRODUCT_CATEGORY',
  P_PRODUCT_DETAIL: 'P_PRODUCT_DETAIL',
  P_CATEGORY: 'P_CATEGORY',
  P_CATEGORY_DETAIL: 'P_CATEGORY_DETAIL',
  P_CART: 'P_CART',
  P_POPUP_MENU: 'P_POPUP_MENU',
  P_SUPPORT: 'P_SUPPORT',
};
